name: Checks
on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          scope: "@learn49"

      - name: Ensure access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Install dependencies"
        run: npm install

      - name: "Building"
        run: npm run build

      - name: "Figuring out the packages versions"
        run: npm run publish-stable

      - name: "Publish NPM Package"
        run: npx lerna exec --no-bail -- npm publish

      - name: "Setup npm" # Add our registry to npm config
        run: npm --version
