name: Checks
on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          scope: "@learn49"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci

      - name: Ensure access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Building"
        run: npm run build

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: "Figuring out the packages versions"
        run: npm run publish-stable

      - name: "Publish NPM Package"
        run: npx lerna publish from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
